opt_in_rules:
- force_try
- force_cast

disabled_rules:
- type_name
- line_length
- cyclomatic_complexity
- identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
